name: market_pipe
version: 1.0.0
config-version: 2

profile: market_pipe

model-paths:
  - models
target-path: target
packages-install-path: dbt_packages
clean-targets:
  - target
  - dbt_packages
on-run-start:
  - "drop view if exists staging.stg_coingecko__coins_list cascade"
  - "drop view if exists staging.stg_coingecko__asset_platforms cascade"
  - "drop view if exists marts.dim_coins cascade"
  - "drop view if exists marts.dim_asset_platforms cascade"

models:
  market_pipe:
    +materialized: view
    staging:
      coingecko:
        +schema: coingecko
    marts:
      coingecko:
        +schema: coingecko
